services:
  postgres:
    image: postgres:17
    container_name: data-governance-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: governance
      POSTGRES_PASSWORD: governance_dev
      POSTGRES_DB: governance

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    build:
      context: ../dbt
      dockerfile: Dockerfile

    container_name: data-governance-dbt
    restart: unless-stopped

    working_dir: /usr/app/dbt

    volumes:
      - ../dbt:/usr/app/dbt

    depends_on:
      - postgres

volumes:
  postgres_data: