version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: olist_customers
      - name: olist_orders
      - name: olist_order_items
      - name: olist_products
      - name: olist_product_category_translation